import React, { useState, useEffect } from 'react';
import { 
  X, Send, Copy, Check, MessageSquare, Car, DollarSign, 
  ShieldCheck, Receipt, Sparkles, Building, Phone, Edit3, 
  RotateCcw, Eye, Type, AlertCircle
} from 'lucide-react';
import { buildPaymentDueReminderWhatsAppMessage, buildPaymentConfirmationWhatsAppMessage, formatINR } from '../utils/whatsapp';

export default function ConsolidatedReminderModal({
  isOpen,
  onClose,
  initialCustomerName = '',
  initialPhone = '',
  initialVehicles = [],
  stockPlace = '',
  initialMode = 'REMINDER' // 'REMINDER' | 'CONFIRMATION'
}) {
  if (!isOpen) return null;

  const [mode, setMode] = useState(initialMode); // 'REMINDER' | 'CONFIRMATION'
  const [customerName, setCustomerName] = useState(initialCustomerName || 'Valued Customer');
  const [phone, setPhone] = useState(initialPhone || '');
  const [paymentMode, setPaymentMode] = useState('UPI / PhonePe');
  const [paymentDate, setPaymentDate] = useState(() => new Date().toISOString().split('T')[0]);
  const [copied, setCopied] = useState(false);

  // Live editing of WhatsApp message text
  const [isEditingMessage, setIsEditingMessage] = useState(false);
  const [customMessage, setCustomMessage] = useState('');
  const [hasUserCustomized, setHasUserCustomized] = useState(false);

  // Selected vehicle items state with normalized costs & GST
  const [vehicleItems, setVehicleItems] = useState([]);

  useEffect(() => {
    setCustomerName(initialCustomerName || 'Valued Customer');
    setPhone(initialPhone || '');
    setMode(initialMode || 'REMINDER');
    setIsEditingMessage(false);
    setHasUserCustomized(false);

    // Normalize vehicles input
    const normalized = (initialVehicles || []).map((v, idx) => {
      const attrs = v.additional_attributes || {};
      const vehNo = v.vehicleNumber || v.vehicle_number || attrs['VEHICLE NUMBER'] || attrs['Vehicle Number'] || `Vehicle ${idx + 1}`;
      const imei = v.imei || v.imei_number || '';
      
      let base = parseFloat(v.cost || attrs['COST'] || attrs['Cost'] || 0);
      let total = parseFloat(v.totalCost || v.total_cost || attrs['TOTAL COST'] || attrs['Total Cost'] || v.sale_price || v.amount || 0);
      let gst = parseFloat(v.gst || attrs['GST'] || attrs['GST AMOUNT'] || 0);

      // Auto-compute GST if total > base and gst is 0
      if (!gst && total > base && base > 0) {
        gst = total - base;
      } else if (!total && base > 0) {
        total = base + gst;
      } else if (!base && total > 0) {
        base = total;
      }

      if (!base && !total) {
        base = 4200;
        gst = 756;
        total = 4956;
      }

      return {
        id: v.id || `${imei}-${idx}`,
        selected: true,
        vehicleNumber: vehNo,
        imei: imei,
        deviceType: v.device_type_name || v.deviceType || 'AIS-140 GPS',
        baseCost: base,
        gst: gst,
        totalCost: total
      };
    });

    setVehicleItems(normalized);
  }, [initialCustomerName, initialPhone, initialVehicles, initialMode, isOpen]);

  // Selected vehicles calculation
  const selectedItems = vehicleItems.filter(v => v.selected);
  const totalVehiclesCount = selectedItems.length;
  const sumBaseCost = selectedItems.reduce((acc, v) => acc + (parseFloat(v.baseCost) || 0), 0);
  const sumGst = selectedItems.reduce((acc, v) => acc + (parseFloat(v.gst) || 0), 0);
  const sumGrandTotal = selectedItems.reduce((acc, v) => acc + (parseFloat(v.totalCost) || 0), 0);

  // Toggle selection
  const handleToggleItem = (id) => {
    setVehicleItems(prev => prev.map(item => item.id === id ? { ...item, selected: !item.selected } : item));
  };

  const handleToggleSelectAll = () => {
    const allSelected = vehicleItems.every(v => v.selected);
    setVehicleItems(prev => prev.map(item => ({ ...item, selected: !allSelected })));
  };

  // Update item cost / GST
  const handleUpdateItem = (id, field, value) => {
    setVehicleItems(prev => prev.map(item => {
      if (item.id !== id) return item;
      const updated = { ...item, [field]: value };
      const base = parseFloat(field === 'baseCost' ? value : updated.baseCost) || 0;
      const gst = parseFloat(field === 'gst' ? value : updated.gst) || 0;
      updated.totalCost = base + gst;
      return updated;
    }));
  };

  // Build generated message from state
  const currentPayload = {
    phone: phone.trim(),
    customerName: customerName.trim(),
    stockPlace: stockPlace,
    paymentMode: paymentMode,
    confirmationDate: paymentDate,
    vehicles: selectedItems.map(v => ({
      vehicleNumber: v.vehicleNumber,
      imei: v.imei,
      cost: v.baseCost,
      gst: v.gst,
      totalCost: v.totalCost
    }))
  };

  const autoGeneratedMessage = (mode === 'REMINDER'
    ? buildPaymentDueReminderWhatsAppMessage(currentPayload)
    : buildPaymentConfirmationWhatsAppMessage(currentPayload)).message;

  // Sync with auto-generated message if user hasn't explicitly customized
  useEffect(() => {
    if (!hasUserCustomized) {
      setCustomMessage(autoGeneratedMessage);
    }
  }, [autoGeneratedMessage, hasUserCustomized]);

  const activeMessageText = hasUserCustomized ? customMessage : autoGeneratedMessage;

  const handleResetToDefault = () => {
    setHasUserCustomized(false);
    setCustomMessage(autoGeneratedMessage);
  };

  const handleSendWhatsApp = () => {
    const cleanDigits = phone ? String(phone).replace(/[^0-9]/g, '') : '';
    const targetPhone = cleanDigits.length === 10 ? `91${cleanDigits}` : cleanDigits;

    if (!cleanDigits) {
      alert('Please enter a valid 10-digit customer phone number to send WhatsApp message.');
      return;
    }
    if (selectedItems.length === 0) {
      alert('Please select at least 1 vehicle to include in the reminder.');
      return;
    }

    const url = targetPhone
      ? `https://api.whatsapp.com/send?phone=${targetPhone}&text=${encodeURIComponent(activeMessageText)}`
      : `https://api.whatsapp.com/send?text=${encodeURIComponent(activeMessageText)}`;

    window.open(url, '_blank');
  };

  const handleCopyMessage = () => {
    navigator.clipboard.writeText(activeMessageText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/70 backdrop-blur-xs flex items-center justify-center p-3 sm:p-5 animate-in fade-in duration-200">
      <div className="bg-white border border-slate-200 rounded-3xl w-full max-w-5xl shadow-2xl overflow-hidden flex flex-col max-h-[92vh]">
        
        {/* Header */}
        <div className="px-6 py-4 bg-slate-900 text-white flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className={`w-10 h-10 rounded-2xl flex items-center justify-center text-white shadow-md ${
              mode === 'REMINDER' ? 'bg-amber-500' : 'bg-emerald-600'
            }`}>
              {mode === 'REMINDER' ? <MessageSquare className="w-5 h-5" /> : <Receipt className="w-5 h-5" />}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-bold text-white">
                  {mode === 'REMINDER' ? 'Consolidated Fleet Payment Due Reminder' : 'Consolidated Payment Confirmation Receipt'}
                </h3>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-white/10 text-slate-200">
                  {totalVehiclesCount} Selected Vehicles
                </span>
              </div>
              <p className="text-xs text-slate-400">
                {mode === 'REMINDER'
                  ? 'Send 1 single WhatsApp message for the total customer balance with GST & vehicle breakdown'
                  : 'Send 1 single WhatsApp payment confirmation and receipt for multiple vehicles'}
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-white rounded-xl hover:bg-white/10 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Mode Selector Tabs & Customer Details Bar */}
        <div className="p-4 bg-slate-50 border-b border-slate-200 grid grid-cols-1 md:grid-cols-3 gap-3">
          
          {/* Mode Switcher */}
          <div className="flex items-center bg-slate-200/80 p-1 rounded-xl">
            <button
              onClick={() => {
                setMode('REMINDER');
                setHasUserCustomized(false);
              }}
              className={`flex-1 py-1.5 text-xs font-bold rounded-lg transition-all flex items-center justify-center gap-1.5 cursor-pointer ${
                mode === 'REMINDER'
                  ? 'bg-amber-500 text-white shadow-xs'
                  : 'text-slate-700 hover:text-slate-900'
              }`}
            >
              <span>🔔 Payment Due Reminder</span>
            </button>
            <button
              onClick={() => {
                setMode('CONFIRMATION');
                setHasUserCustomized(false);
              }}
              className={`flex-1 py-1.5 text-xs font-bold rounded-lg transition-all flex items-center justify-center gap-1.5 cursor-pointer ${
                mode === 'CONFIRMATION'
                  ? 'bg-emerald-600 text-white shadow-xs'
                  : 'text-slate-700 hover:text-slate-900'
              }`}
            >
              <span>✅ Payment Confirmation</span>
            </button>
          </div>

          {/* Customer Name */}
          <div className="relative">
            <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block mb-1">Customer / Fleet Name</label>
            <input
              type="text"
              value={customerName}
              onChange={(e) => setCustomerName(e.target.value)}
              className="w-full bg-white border border-slate-300 rounded-xl px-3 py-1.5 text-xs font-semibold text-slate-900 focus:outline-none focus:border-indigo-500"
              placeholder="Customer Name"
            />
          </div>

          {/* Customer Mobile */}
          <div className="relative">
            <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block mb-1">Customer WhatsApp Mobile</label>
            <div className="relative">
              <Phone className="w-3.5 h-3.5 absolute left-3 top-2.5 text-slate-400" />
              <input
                type="text"
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                className="w-full bg-white border border-slate-300 rounded-xl pl-8 pr-3 py-1.5 text-xs font-mono font-bold text-indigo-900 focus:outline-none focus:border-indigo-500"
                placeholder="10-digit mobile number"
              />
            </div>
          </div>
        </div>

        {/* Main Content: Vehicle Table & Realtime WhatsApp Preview / Editor */}
        <div className="flex-1 overflow-y-auto p-5 grid grid-cols-1 lg:grid-cols-12 gap-5">
          
          {/* Left Column: Fleet Breakdown Table */}
          <div className="lg:col-span-6 space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-slate-900 uppercase tracking-wider">Fleet Vehicles Breakdown</span>
                <span className="text-[11px] font-bold text-indigo-700 bg-indigo-50 px-2 py-0.5 rounded-full border border-indigo-200">
                  {selectedItems.length} of {vehicleItems.length} Included
                </span>
              </div>
              <button
                onClick={handleToggleSelectAll}
                className="text-xs text-indigo-600 hover:text-indigo-800 font-bold hover:underline cursor-pointer"
              >
                {vehicleItems.every(v => v.selected) ? 'Deselect All' : 'Select All'}
              </button>
            </div>

            <div className="border border-slate-200 rounded-2xl overflow-hidden shadow-2xs max-h-[290px] overflow-y-auto">
              <table className="w-full text-left text-xs border-collapse">
                <thead className="bg-slate-100 text-slate-700 font-bold sticky top-0 z-10 border-b border-slate-200">
                  <tr>
                    <th className="p-2.5 w-8 text-center">
                      <input
                        type="checkbox"
                        checked={vehicleItems.length > 0 && vehicleItems.every(v => v.selected)}
                        onChange={handleToggleSelectAll}
                        className="rounded text-indigo-600"
                      />
                    </th>
                    <th className="p-2.5">Vehicle & IMEI</th>
                    <th className="p-2.5 w-24">Base Cost</th>
                    <th className="p-2.5 w-20">GST (18%)</th>
                    <th className="p-2.5 w-24 text-right">Total Due</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 bg-white">
                  {vehicleItems.length === 0 ? (
                    <tr>
                      <td colSpan={5} className="p-6 text-center text-xs text-slate-400">
                        No vehicle records attached to this customer.
                      </td>
                    </tr>
                  ) : (
                    vehicleItems.map((item) => (
                      <tr
                        key={item.id}
                        className={`hover:bg-slate-50 transition-colors ${
                          item.selected ? 'bg-indigo-50/30' : 'opacity-60 bg-slate-50/50'
                        }`}
                      >
                        <td className="p-2.5 text-center" onClick={(e) => e.stopPropagation()}>
                          <input
                            type="checkbox"
                            checked={item.selected}
                            onChange={() => handleToggleItem(item.id)}
                            className="rounded text-indigo-600 cursor-pointer"
                          />
                        </td>
                        <td className="p-2.5">
                          <div className="font-bold text-slate-900 flex items-center gap-1.5">
                            <Car className="w-3.5 h-3.5 text-amber-600" />
                            <span>{item.vehicleNumber}</span>
                          </div>
                          <div className="text-[10px] font-mono text-slate-500">
                            IMEI: {item.imei || '-'}
                          </div>
                        </td>
                        <td className="p-2.5 font-mono">
                          <input
                            type="number"
                            value={item.baseCost}
                            onChange={(e) => handleUpdateItem(item.id, 'baseCost', e.target.value)}
                            className="w-full bg-slate-50 border border-slate-200 rounded px-1.5 py-1 text-xs font-bold text-slate-800 focus:outline-none focus:bg-white"
                          />
                        </td>
                        <td className="p-2.5 font-mono">
                          <input
                            type="number"
                            value={item.gst}
                            onChange={(e) => handleUpdateItem(item.id, 'gst', e.target.value)}
                            className="w-full bg-slate-50 border border-slate-200 rounded px-1.5 py-1 text-xs font-bold text-amber-800 focus:outline-none focus:bg-white"
                          />
                        </td>
                        <td className="p-2.5 text-right font-mono font-bold text-slate-900">
                          {formatINR(item.totalCost)}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            {/* Financial Summary Card */}
            <div className="bg-linear-to-r from-slate-900 to-indigo-950 text-white p-4 rounded-2xl shadow-md space-y-2">
              <div className="flex items-center justify-between text-xs text-slate-300">
                <span>📦 Total Active Fleet:</span>
                <span className="font-bold text-white font-mono">{totalVehiclesCount} Vehicles</span>
              </div>
              <div className="flex items-center justify-between text-xs text-slate-300">
                <span>💵 Base Equipment Cost:</span>
                <span className="font-bold text-slate-200 font-mono">{formatINR(sumBaseCost)}</span>
              </div>
              {sumGst > 0 && (
                <div className="flex items-center justify-between text-xs text-amber-300">
                  <span>📑 GST (18%):</span>
                  <span className="font-bold font-mono">{formatINR(sumGst)}</span>
                </div>
              )}
              <div className="border-t border-slate-700/80 pt-2 flex items-center justify-between text-sm">
                <span className="font-bold text-amber-400">💰 {mode === 'REMINDER' ? 'GRAND TOTAL DUE:' : 'TOTAL RECEIVED:'}</span>
                <span className="font-black text-xl text-emerald-400 font-mono">{formatINR(sumGrandTotal)}</span>
              </div>
            </div>
          </div>

          {/* Right Column: Live WhatsApp Message Preview / Direct Live Text Editor */}
          <div className="lg:col-span-6 space-y-3 flex flex-col">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5">
                  <Sparkles className="w-3.5 h-3.5 text-emerald-600" /> WhatsApp Live Preview
                </span>
                {hasUserCustomized && (
                  <span className="px-2 py-0.5 rounded-full bg-indigo-100 text-indigo-800 text-[10px] font-bold">
                    ✏️ Custom Edited
                  </span>
                )}
              </div>

              <div className="flex items-center gap-1.5">
                {/* Toggle Direct Text Editor */}
                <button
                  type="button"
                  onClick={() => setIsEditingMessage(!isEditingMessage)}
                  className={`px-2.5 py-1 rounded-lg text-xs font-bold flex items-center gap-1 transition-colors cursor-pointer border ${
                    isEditingMessage
                      ? 'bg-indigo-600 text-white border-indigo-600 shadow-xs'
                      : 'bg-white hover:bg-slate-100 text-slate-700 border-slate-200'
                  }`}
                  title="Directly edit and customize the WhatsApp text"
                >
                  <Edit3 className="w-3 h-3" />
                  <span>{isEditingMessage ? '👁️ Done Editing' : '✏️ Edit Text'}</span>
                </button>

                {/* Reset to Default */}
                {hasUserCustomized && (
                  <button
                    type="button"
                    onClick={handleResetToDefault}
                    className="px-2 py-1 rounded-lg bg-amber-50 hover:bg-amber-100 text-amber-800 border border-amber-200 text-xs font-bold flex items-center gap-1 transition-colors cursor-pointer"
                    title="Reset message back to auto-calculated fleet breakdown"
                  >
                    <RotateCcw className="w-3 h-3" />
                    <span>Reset</span>
                  </button>
                )}

                {/* Copy Text */}
                <button
                  type="button"
                  onClick={handleCopyMessage}
                  className="px-2.5 py-1 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold flex items-center gap-1 transition-colors cursor-pointer border border-slate-200"
                  title="Copy message to clipboard"
                >
                  {copied ? <Check className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3" />}
                  <span>{copied ? 'Copied!' : 'Copy'}</span>
                </button>
              </div>
            </div>

            {/* Editable Textarea OR Chat Bubble */}
            {isEditingMessage ? (
              <div className="flex-1 flex flex-col space-y-2">
                <textarea
                  value={activeMessageText}
                  onChange={(e) => {
                    setCustomMessage(e.target.value);
                    setHasUserCustomized(true);
                  }}
                  rows={15}
                  className="w-full flex-1 bg-white p-3.5 border-2 border-indigo-500 rounded-2xl text-xs font-mono text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-400 shadow-inner resize-none leading-relaxed"
                  placeholder="Type or customize your WhatsApp message here..."
                />
                <div className="flex items-center justify-between text-[11px] text-slate-500 px-1">
                  <span>✏️ <strong>Live Text Editor</strong>: Whatever you edit above is what will be sent to the customer on WhatsApp.</span>
                  <span className="font-mono text-indigo-700 font-bold">{activeMessageText.length} chars</span>
                </div>
              </div>
            ) : (
              <div 
                onClick={() => setIsEditingMessage(true)}
                className="flex-1 bg-[#EFEAE2] p-4 rounded-2xl border border-slate-200/80 shadow-inner overflow-y-auto max-h-[360px] cursor-pointer group relative"
                title="Click to directly edit this WhatsApp message"
              >
                <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity bg-slate-900/80 text-white text-[10px] font-bold px-2 py-1 rounded-md flex items-center gap-1">
                  <Edit3 className="w-3 h-3" /> Click to Edit Message
                </div>
                <div className="bg-white rounded-2xl rounded-tl-none p-3.5 shadow-sm text-xs font-mono text-slate-800 whitespace-pre-wrap leading-relaxed border border-slate-100">
                  {activeMessageText}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="text-xs text-slate-500">
            {phone ? (
              <span>Sending to: <strong className="text-indigo-700 font-mono font-bold">+91 {phone}</strong></span>
            ) : (
              <span className="text-red-500 font-bold">⚠️ Please enter customer mobile number above</span>
            )}
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-4 py-2 bg-slate-200 hover:bg-slate-300 text-slate-700 rounded-xl text-xs font-bold transition-colors cursor-pointer"
            >
              Close
            </button>

            <button
              onClick={handleSendWhatsApp}
              disabled={selectedItems.length === 0}
              className={`px-5 py-2 text-white rounded-xl text-xs font-bold flex items-center gap-2 shadow-md transition-all cursor-pointer ${
                mode === 'REMINDER'
                  ? 'bg-amber-600 hover:bg-amber-700 active:scale-98'
                  : 'bg-emerald-600 hover:bg-emerald-700 active:scale-98'
              }`}
            >
              <span>💬</span>
              <span>{mode === 'REMINDER' ? 'Send Consolidated Reminder' : 'Send Payment Confirmation'}</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
